title: Welcome!
author: Kebin Jorquera Rojas
email: kebin172001@gmail.com
description: Soy chileno y estudio Ingeniería Civil Informática
theme: minima 
# social links
twitter_username: kebinjr17
github_username: Kebin17


